### ISSUE TITLE
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet

### ISSUE THREAD

**Issue by kolanos** [simplyopen-it/django-admin-reports#23]
For django >=2.1.0:

```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File ".../.virtualenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File ".../.virtualenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File ".../.virtualenv/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File ".../.virtualenv/lib/python3.7/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File ".../.virtualenv/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File ".../.virtualenv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".../.virtualenv/lib/python3.7/site-packages/admin_reports/__init__.py", line 3, in <module>
    from .sites import AdminReportSite, site
  File ".../.virtualenv/lib/python3.7/site-packages/admin_reports/sites.py", line 3, in <module>
    from .views import ReportView
  File ".../.virtualenv/lib/python3.7/site-packages/admin_reports/views.py", line 21, in <module>
    admin_view_m = method_decorator(site.admin_view)
  File ".../.virtualenv/lib/python3.7/site-packages/django/utils/functional.py", line 213, in inner
    self._setup()
  File ".../.virtualenv/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 526, in _setup
    AdminSiteClass = import_string(apps.get_app_config('admin').default_site)
  File ".../.virtualenv/lib/python3.7/site-packages/django/apps/registry.py", line 150, in get_app_config
    self.check_apps_ready()
  File ".../.virtualenv/lib/python3.7/site-packages/django/apps/registry.py", line 132, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

Appears to be a result of the site imports in `admin_reports/__init__.py`.

**Comment by ludovicthomas** [comment]
Issue seems to have been fixed on a new package named `django-admin-reports`.

Follow these steps:

```
pip uninstall admin-reports
pip install django-admin-reports
```

You will get django-admin-reports v0.11.0 working properly.

**Comment by oberix** [comment]
Yes, the package has been renamed both because it was very hard to keep it backward compatible with django < 1.11, and I needed a compatible package, and to comply to the naming convention for django packages in pypi 

thanks for highlighting this
